### ISSUE TITLE
Account name is no longer shown in the status bar

### ISSUE THREAD

**Issue by calebplum** [yaggytter/chrome-extension-awssso#16]
As of today, the AWS status bar is no longer showing the name of the account I'm currently in. It only shows `role/username`, for example `AWSAdministratorAccess/user@domain.com`.

Changing the colour of the status bar according to the account name has also stopped working, for example with this config:

```
{
  ".*production.*": "red"
}
```

Is this happening to anyone else? Does anyone have a fix?

**Comment by hellsp** [comment]
same to me, guess it's because of Chrome upgrade? I'm currently on `Version 113.0.5672.126 (Official Build) (x86_64)
`

**Comment by MrFishFinger** [comment]
i am also experiencing this issue, but have not yet updated Chrome to the latest version.  i am still on `112.0.5615.49 (Offizieller Build) (x86_64)`.

maybe AWS changed something in the console page (or API), that the plugin uses to obtain that information?

**Comment by MrFishFinger** [comment]
i am also experiencing this issue, but with the plugin on **Firefox** (version `112.0.2`) - so i guess the issue is not browser-specific.

maybe AWS changed something in the console page (or API), that the plugin uses to obtain that information?

**Comment by yaggytter** [comment]
Thank you for the information. I also realized this problem today. So I will investigate and fix this issue by the weekend.

**Comment by jr-ri** [comment]
I'm having the same issue in Chrome. I followed up by testing the Firefox version of the extension, and it's not working there either.
Since it's broken in both browsers (and the code in [the Firefox directory](https://github.com/yaggytter/chrome-extension-awssso/tree/forfirefox) hasn't changed since 2021), I'm inclined to agree with @MrFishFinger about this (possibly) being due to a change/issue on AWS's side.

This may be related to the API changes associated with AWS migrating from `AWS SSO` to `AWS IAM Identity Center`:
* https://aws.amazon.com/about-aws/whats-new/2022/09/aws-iam-identity-center-apis-manage-users-groups-scale/
* https://aws.amazon.com/blogs/security/get-ready-upcoming-changes-aws-single-sign-on-user-sign-in-process/

**Comment by djablonski-moia** [comment]
It worked also with AWS IAM Identity Center until last week, so I would guess it's just once more a small change in their UI which breaks things here :disappointed: (shame on AWS, not @yaggytter)

**Comment by calebplum** [comment]
Just a note, I access multiple accounts at the same time using Firefox Containers (where each container has a separate cookie store) and I'm seeing the issue intermittently in different sessions and/or AWS accounts. Sometimes a session/account combination will show the account name, and other session/account combinations won't. 

I'm guessing this is because a change to the AWS console is being deployed in an A/B fashion, targeting cookies and/or accounts. So ideally if any fix that's implemented can be backwards-compatible that would provide the widest compatibility. It's anyone's guess how long such an A/B deployment might take AWS to complete, or whether the changes might be reverted at some point in the future.

**Comment by yaggytter** [comment]
I've fixed this and submitted it as version 1.3.1 to the Chrome Web Store. Currently, it's under review. Please wait a while until the review is complete and it's published. Actually, Firefox version is already released. Thank you for your information! 
@calebplum @hellsp @MrFishFinger @jr-ri @djablonski-moia
